version: '2'

services:

    gvm:
        build:
            context: ./gvm
        tty: true
        volumes:
            - ./app:/usr/share/app

    go:
        build:
            context: ./go
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
        tty: true
